version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - php
    reviewers:
      - rickeysxhemz
    groups:
      laravel:
        patterns:
          - "illuminate/*"
          - "laravel/*"
      testing:
        patterns:
          - "pestphp/*"
          - "phpstan/*"
          - "larastan/*"
          - "laravel/pint"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - github-actions
    reviewers:
      - rickeysxhemz
